sudo: required

language: java

services:
  - docker

jdk: oraclejdk8

before_script: ulimit -u 30000

script:
- gradle clean shadowJar -p $COMPONENT -x test

after_success: $COMPONENT/int_test.sh

env:
  - COMPONENT=kafka-connect-hive