sudo: required

language: java

services:
  - docker

before_install:
  - docker-compose -f $COMPONENT/docker-compose.yml up

jdk: oraclejdk8

before_script: ulimit -u 30000

script:
- gradle clean test -p $COMPONENT

env:
  - COMPONENT=kafka-connect-hive