sudo: required

language: java

services:
  - docker

jdk: oraclejdk8

script: ./gradlew shadowJar --parallel && ./gradlew test

after_success: ./gradlew kafka-connect-hive:shadowJar -x test && ./int_test.sh
